typography_spectrum: 0.42366839153692126
contact_details:
  name: Broseph Mcgee
  phone: '8085555555'
  email: the-greatest@awesome.com
color:
  brandStrength: 0.6191576360724866
  lightness: 0.49714253074489534
  saturation: 0.44853906612843275
  rhythmicContrast: 0.17060956405475736
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.08849682239815593
social_links:
  facebook: 'https://www.facebook.com/sam.ghadiri?hc_ref=NEWSFEED'
  twitter: 'https://www.facebook.com/sam.ghadiri?hc_ref=NEWSFEED'
  instagram: 'https://www.facebook.com/sam.ghadiri?hc_ref=NEWSFEED'
profiles:
  - id: 4ad4a11d-71ab-488e-a3c8-1a8c8bb4aa44
    name: SpaceX landing
    type: content
    rel: footer
  - id: 42e9ebc5-424e-494c-ada4-0fe79e5f7856
    name: 20 Greatest Feats of Boeing
    type: content
    rel: footer
  - url: >-
      http://localhost:3000/app/footer-nav/url?siteID=1fc3477b-ece3-43d1-90e5-ad00e13885cf
    name: About Us
    type: external
    rel: footer
  - url: >-
      http://localhost:3000/app/footer-nav/url?siteID=1fc3477b-ece3-43d1-90e5-ad00e13885cfsss
    name: Best of
    type: external
    rel: footer
name: abnormal bitterness
navigation:
  - name: our pick of the finest
    id: 90c0070f-c08a-4b27-930f-fe1dad65484c
    type: content
  - name: 100 Years of Boeing
    id: 42e9ebc5-424e-494c-ada4-0fe79e5f7856
    type: content
  - name: Picture Quotes To Supercharge Your Creativity
    id: c09b68b3-8210-472e-97ac-51046fa6b7dd
    type: content
title: Abnormal is the new normal
description: Don't rain on my parade
purpose:
  - id: d1e4e419-c183-4949-838d-99d3ac7da38a
    type: external
    value: 'http://tympanus.net/Development/MorphingDevices/'
    label: Sign-up
