layout_spectrum: 0.08849682239815593
typography_spectrum: 0.42366839153692126
color:
  brandStrength: 0.6191576360724866
  lightness: 0.49714253074489534
  saturation: 0.44853906612843275
  rhythmicContrast: 0.17060956405475736
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: abnormal bitterness
navigation:
  - url: google.com
    title: About
